# Generated by Django 2.2.6 on 2019-10-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('balance', models.FloatField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(default=0)),
                ('pin', models.IntegerField()),
                ('date_issued', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmsite.Account')),
            ],
        ),
    ]
